### ISSUE TITLE
Stream to browser without OBS?

### ISSUE THREAD

**Issue by allesan** [puhitaku/mtplvcap#79]
Is it possible to somehow bypass OBS and have Firefox detect my camera without OBS?

**Comment by puhitaku** [comment]
The browsers rely on the OS's video recording device API, but mtplvcap doesn't have a mechanism to connect the video stream from DSLRs to the API. OBS's virtual camera takes that part, so you can't "bypass" it since it's necessary.

Since it needs different OS-dependent code or each OS to connect mtplvcap to the video recording API, that's very heavy and I will only do it if someone gives me that part with CI support.
